schemaVersion: 2.1.0
metadata:
  name: php-hello-world
components:
  - name: tools
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.10
      memoryLimit: '2Gi'
      memoryRequest: '1Gi'
      cpuLimit: '1'
      cpuRequest: '0.5'

commands:
  - id: hello
    exec:
      label: "Hello World"
      component: tools
      commandLine: php hello-world.php
      group:
        kind: run
  - id: ls
    exec:
      label: "list directory"
      component: tools
      commandLine: ls
      group:
        kind: run
